version: 2.1

jobs:
  lint-app:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
  build-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker container for each microservices
          command: |
            echo "--------- Installing dependencies-----------"
            sudo curl -LO https://nodejs.org/dist/v18.0.0/node-v18.0.0-linux-x64.tar.xz
            sudo tar -xvf node-v18.0.0-linux-x64.tar.xz
            sudo cp -r node-v18.0.0-linux-x64/{bin,include,lib,share} /usr/
            node --version => v18.0.0
            sudo apt install nodejs

            echo "--------- The images is Building ------------"
            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed omar00101/udagram-api-feed:v6

            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user omar00101/udagram-api-user:v6
            
            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend omar00101/udagram-frontend:v7

            docker build -t udagram-reverseproxy ./udagram-reverseproxy
            docker tag udagram-reverseproxy omar00101/udagram-reverseproxy:v6

            echo "-------- All images succesfully built----------"
            
            echo " ------- login in to hub--------"
            echo $DOCKER_PASSWORD | docker login -u omar00101 --password-stdin
            
            echo "-------------- Pushing images to dockerhub-------"
            docker push omar00101/udagram-api-feed:v6
            docker push omar00101/udagram-api-user:v6
            docker push omar00101/udagram-frontend:v7
            docker push omar00101/udagram-reverseproxy:v6
workflows:
  default:
    jobs:
      - lint-app
      - build-docker:
          requires: [lint-app]
