apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-secret
# type: Opaque
data:
  # credentials: QVNJQVNFWkpRNkpWU1lJM0NPRzIKZmZZZWk1eVVDQXRKMnpsam9SS2dkdjhwejUxVllqekRoKzVkQjgrSwo=
  # cat ~/.aws/credentials | tail -n 6 | head -n 2 | base64
  # YXdzX2FjY2Vzc19rZXlfaWQgPSBBU0lBU0VaSlE2SlZTWUkzQ09HMgphd3Nfc2VjcmV0X2FjY2Vz
  # c19rZXkgPSBmZlllaTV5VUNBdEoyemxqb1JLZ2R2OHB6NTFWWWp6RGgrNWRCOCtLCg==

  #  echo 'aws_access_key_id = ASIASEZJQ6JVSYI3COG2' | base64
  # YXdzX2FjY2Vzc19rZXlfaWQgPSBBU0lBU0VaSlE2SlZTWUkzQ09HMgo=
  # echo 'aws_secret_access_key = ffYei5yUCAtJ2zljoRKgdv8pz51VYjzDh+5dB8+K' | base64
  # YXdzX3NlY3JldF9hY2Nlc3Nfa2V5ID0gZmZZZWk1eVVDQXRKMnpsam9SS2dkdjhwejUxVllqekRo
  # KzVkQjgrSwo=

  # echo 'ASIASEZJQ6JVSYI3COG2' | base64
  # QVNJQVNFWkpRNkpWU1lJM0NPRzIK
  # echo 'ffYei5yUCAtJ2zljoRKgdv8pz51VYjzDh+5dB8+K' | base64
  # ZmZZZWk1eVVDQXRKMnpsam9SS2dkdjhwejUxVllqekRoKzVkQjgrSwo=
  
  # https://www.base64encode.org/
  # YXdzX2FjY2Vzc19rZXlfaWQgPSBBU0lBU0VaSlE2SlZTWUkzQ09HMgphd3Nfc2VjcmV0X2FjY2Vzc19rZXkgPSBmZlllaTV5VUNBdEoyemxqb1JLZ2R2OHB6NTFWWWp6RGgrNWRCOCtL
  # 
  # aws_access_key_id = ASIASEZJQ6JVSYI3COG2 >> YXdzX2FjY2Vzc19rZXlfaWQgPSBBU0lBU0VaSlE2SlZTWUkzQ09HMg==
  # aws_secret_access_key = ffYei5yUCAtJ2zljoRKgdv8pz51VYjzDh+5dB8+K >> YXdzX3NlY3JldF9hY2Nlc3Nfa2V5ID0gZmZZZWk1eVVDQXRKMnpsam9SS2dkdjhwejUxVllqekRoKzVkQjgrSw==

  # ASIASEZJQ6JVSYI3COG2 >> QVNJQVNFWkpRNkpWU1lJM0NPRzI=
  # ffYei5yUCAtJ2zljoRKgdv8pz51VYjzDh+5dB8+K >> ZmZZZWk1eVVDQXRKMnpsam9SS2dkdjhwejUxVllqekRoKzVkQjgrSw==

  # ASIASEZJQ6JVSYI3COG2ffYei5yUCAtJ2zljoRKgdv8pz51VYjzDh+5dB8+K >> QVNJQVNFWkpRNkpWU1lJM0NPRzJmZlllaTV5VUNBdEoyemxqb1JLZ2R2OHB6NTFWWWp6RGgrNWRCOCtL

  credentials: |
    [default]
    aws_session_token = FwoGZXIvYXdzEJH//////////wEaDAbL27lRAqag5AYIQyLVARF9TNpLPDELecJvYtmOcKgRtTli3wPz1jSqrPI893T49ut64E/JG83mzjxGruBtBL8dE74viyoizQxYnqZoCs+FFq2B4XV1U7LpHJrrBUsLf7hoqTk2VwBprtqM2T95n1rabQdvjU/Whc6MzqOPynJWpk9/s6RNIJUlIMzTgQ0GFlkT6pO+FCcLEMYyKnPbGIoY9dlxH2N5ITDbnhZye9sIH2EW8il5Z2LSVGY2vTYxS+7xPL2/+dhg+XeIatO7cfKhTUpWruRFs45+q3eNQUSXEGKXLCi7ofyaBjIt1LqVKS38OCz5urUUhlgEATrwhSHW4R1CsuFMP8uZeyXk0Y7hr2kxZkuDbgLa
    aws_access_key_id = ASIASEZJQ6JVSYI3COG2
    aws_secret_access_key = ffYei5yUCAtJ2zljoRKgdv8pz51VYjzDh+5dB8+K